# Cincinnati, OH

In [40]:
#2020-10-02 last updated
import pandas as pd
cin = pd.read_csv('PDI__Police_Data_Initiative__Crime_Incidents.csv', parse_dates=['DATE_REPORTED'])

C:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (8,17) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [41]:
cin.columns = cin.columns.str.lower().str.replace(" ", "_")

In [42]:
cin.head()

,instanceid,incident_no,date_reported,date_from,date_to,clsd,ucr,dst,beat,offense,...,victim_gender,suspect_age,suspect_race,suspect_ethnicity,suspect_gender,totalnumbervictims,totalsuspects,ucr_group,community_council_neighborhood,zip
0,75092BE1-203C-4251-A197-6A4CD492E803,129023054,2012-08-15 19:40:00,08/15/2012 01:00:00 AM,08/15/2012 09:00:00 AM,Z--EARLY CLOSED,551.0,2,1,BURGLARY,...,FEMALE,UNKNOWN,NaN,NaN,NaN,1.0,NaN,BURGLARY/BREAKING ENTERING,NaN,45206.0
1,D229DDF6-0F66-4AC5-AD13-7F83D2566A91,179006481,2017-03-02 17:16:00,03/02/2017 05:10:00 PM,03/02/2017 05:15:00 PM,J--CLOSED,810.0,3,2,ASSAULT,...,MALE,31-40,WHITE,NOT OF HISPANIC ORIG,MALE,1.0,1.0,PART 2 MINOR,NaN,45205.0
2,961D1BFE-C1BB-4B44-A8F9-2599F7C83249,179020029,2017-06-01 10:35:00,06/01/2017 10:25:00 AM,06/01/2017 10:30:00 AM,J--CLOSED,600.0,5,2,THEFT,...,MALE,UNKNOWN,NaN,NaN,NaN,1.0,NaN,THEFT,NaN,45225.0
3,847165DB-0557-4E36-8692-900D6C456055,129005579,2012-03-04 03:11:00,03/04/2012 03:10:00 AM,03/04/2012 03:11:00 AM,F--CLEARED BY ARREST - ADULT,301.0,5,1,ROBBERY,...,MALE,UNKNOWN,UNKNOWN,UNKNOWN,MALE,1.0,1.0,ROBBERY,NaN,45219.0
4,C1292536-04EB-42BC-9B80-263D731ABD0E,179053792,2017-12-17 09:53:00,12/10/2017 06:00:00 PM,12/11/2017 08:00:00 AM,Z--EARLY CLOSED,600.0,5,2,THEFT,...,MALE,UNKNOWN,NaN,NaN,NaN,2.0,NaN,THEFT,NaN,45225.0

In [43]:
cin = cin.rename(columns={'instanceid': 'city', 'date_reported': 'date', 'offense': 'crime_category'})

In [44]:
cin.columns

Index(['city', 'incident_no', 'date', 'date_from', 'date_to', 'clsd', 'ucr',
       'dst', 'beat', 'crime_category', 'location', 'theft_code', 'floor',
       'side', 'opening', 'hate_bias', 'dayofweek', 'rpt_area',
       'cpd_neighborhood', 'sna_neighborhood', 'weapons', 'date_of_clearance',
       'hour_from', 'hour_to', 'address_x', 'longitude_x', 'latitude_x',
       'victim_age', 'victim_race', 'victim_ethnicity', 'victim_gender',
       'suspect_age', 'suspect_race', 'suspect_ethnicity', 'suspect_gender',
       'totalnumbervictims', 'totalsuspects', 'ucr_group',
       'community_council_neighborhood', 'zip'],
      dtype='object')

In [45]:
cin = cin.loc[:, ['city', 'date', 'crime_category', 'victim_age', 'victim_race', 'victim_ethnicity', 'victim_gender', 'suspect_age', 'suspect_race', 'suspect_ethnicity', 'suspect_gender']]

In [46]:
cin['city'] = 'Cincinnati'

In [48]:
cin = cin[cin.date >= '2020-10-02']

In [49]:
cin.to_csv('../Data_Clean/Cincinnati.csv')

,city,date,crime_category,victim_age,victim_race,victim_ethnicity,victim_gender,suspect_age,suspect_race,suspect_ethnicity,suspect_gender
16,Cincinnati,2020-11-07 13:30:00,THEFT,41-50,BLACK,NOT OF HISPANIC ORIG,FEMALE,UNKNOWN,NaN,NaN,NaN
63,Cincinnati,2020-10-18 13:05:51,THEFT,18-25,WHITE,NOT OF HISPANIC ORIG,MALE,UNKNOWN,NaN,NaN,NaN
81,Cincinnati,2020-10-14 22:12:00,DOMESTIC VIOLENCE,26-30,BLACK,NOT OF HISPANIC ORIG,FEMALE,18-25,BLACK,NOT OF HISPANIC ORIG,MALE
156,Cincinnati,2021-01-11 10:52:00,THEFT,UNKNOWN,NaN,NaN,NaN,UNKNOWN,NaN,NaN,NaN
247,Cincinnati,2020-10-18 07:30:00,ROBBERY,18-25,BLACK,NOT OF HISPANIC ORIG,MALE,UNKNOWN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
436188,Cincinnati,2021-03-23 18:53:58,THEFT,61-70,BLACK,NOT OF HISPANIC ORIG,FEMALE,41-50,BLACK,NOT OF HISPANIC ORIG,MALE
436200,Cincinnati,2021-06-19 20:55:00,ROBBERY,18-25,WHITE,NOT OF HISPANIC ORIG,MALE,26-30,BLACK,NOT OF HISPANIC ORIG,MALE
436206,Cincinnati,2021-03-24 18:01:41,THEFT,UNKNOWN,NaN,NaN,NaN,UNKNOWN,NaN,NaN,NaN
436207,Cincinnati,2021-04-03 14:45:00,AGGRAVATED MENACING,18-25,BLACK,NOT OF HISPANIC ORIG,FEMALE,26-30,BLACK,NOT OF HISPANIC ORIG,MALE
436224,Cincinnati,2020-12-19 19:34:21,FELONIOUS ASSAULT,UNDER 18,BLACK,NOT OF HISPANIC ORIG,MALE,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN