# Fort Worth, TX

In [16]:
#2020-10-04 last update
import pandas as pd
fw = pd.read_csv('Crime_Data.csv', parse_dates=['Reported Date'])

C:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [17]:
fw.columns = fw.columns.str.lower().str.replace(" ", "_")

In [18]:
fw.head()

,case_and_offense,case_number,reported_date,nature_of_call,from_date,offense,description,block_address,city,state,beat,division,council_district,attempt_complete,location_type,location_description,location
0,200051119-90Z,200051119,2020-07-04,PENAL CODE,07/04/2020 10:00:00 AM,90Z,PC 21.07 Public Lewdness 90Z ALL OTHER OFFENSE...,1400 GREEN OAKS RD,FORT WORTH,TX,L11,West,3.0,C,24.0,24 SPECIALTY STORE,NaN
1,200085517-90Z,200085517,2020-11-03,HARASS,08/12/2020 05:18:00 AM,90Z,PC 42.07(C) Harassment,1300 MARLBOROUGH DR,FORT WORTH,TX,I16,South,8.0,C,20.0,20 RESIDENCE/HOME,"(32.640426597727426, -97.33851074771222)"
2,190083263-WAR,190083263,2019-09-24,NARCOTIC VIOLATIONS,09/24/2019 10:30:00 PM,WAR,OT WARRANT Out of Town Warrant WAR Warrants on...,SOUTH FWY,FORT WORTH,TX,I11,South,9.0,C,13.0,13 HIGHWAY/ROAD/ALLEY,NaN
3,190088406-13B,190088406,2019-10-10,SEXUAL ASSAULT,10/10/2019 09:56:32 PM,13B,PC 22.01(A)(1)FV Aslt Causes B/I Family Member...,TANDY AVE / VIEW ST,FORT WORTH,TX,G11,NaN,NaN,C,8.0,08 DEPARTMENT/DISCOUNT STORE,NaN
4,190047946-35A,190047946,2019-06-04,NARCOTIC VIOLATIONS,06/04/2019 01:33:49 AM,35A,HSC 481.117(B) Poss CS PG 3 <28G 35A DRUG/NARC...,OAK GROVE RD / E IH 20 FWY EB,NaN,TX,I17,NaN,NaN,C,13.0,13 HIGHWAY/ROAD/ALLEY,NaN

In [19]:
fw = fw.rename(columns={'reported_date': 'date', 'description': 'crime_category'})

In [20]:
fw['city'] = 'Fort Worth'

In [21]:
fw = fw.loc[:, ['city', 'date', 'crime_category']]

In [22]:
fw = fw[fw.date >= '2020-10-04']

In [23]:
fw.to_csv('../Data_Clean/Fort_Worth.csv')

,city,date,crime_category
1,Fort Worth,2020-11-03,PC 42.07(C) Harassment
160,Fort Worth,2020-10-08,GC 080 Public Intoxication
283,Fort Worth,2020-12-13,PC 28.03(B)(2) Crim Misc>=$100<$750
507,Fort Worth,2020-10-06,GC 088-03 Family or Domestic Violence Assault ...
1458,Fort Worth,2020-11-20,PC 49.04(D) DWI BAC >= 0.15
...,...,...,...
148295,Fort Worth,2021-07-10,PC 28.03(B)(2) Crim Misc>=$100<$750
148296,Fort Worth,2021-07-10,PC 30.04(A) Burglary Vehicle
148297,Fort Worth,2021-07-06,PC 33.02(A) Computer Security Breach
148298,Fort Worth,2021-07-05,PC 28.03(B)(3) Crim Misc>$500<$1500
148299,Fort Worth,2021-07-03,PC 38.04(b) Evading Arrest Detention