# Nashville, TN

In [12]:
import pandas as pd
nv = pd.read_csv('Metro_Nashville_Police_Department_Incidents.csv', parse_dates=['Incident Occurred'])

In [13]:
nv.count()

Primary Key                    872316
Incident Number                872316
Report Type                    872241
Report Type Description        809764
Incident Status Code           872294
Incident Status Description    872294
Investigation Status           872316
Incident Occurred              872316
Incident Reported              872306
Incident Location              869773
Latitude                       848018
Longitude                      848018
ZIP Code                       474689
RPA                            701917
Zone                           701917
Location Code                  872309
Location Description           872309
Offense Number                 872032
Offense NIBRS                  872225
Offense Description            872316
Weapon Primary                 870993
Weapon Description             870265
Victim Number                  872316
Domestic Related               872316
Victim Type                    872298
Victim Description             872222
Victim Gender                  641183
Victim Race                    641183
Victim Ethnicity               641054
Victim County Resident         617498
Mapped Location                848018
dtype: int64

In [14]:
nv.head()

,Primary Key,Incident Number,Report Type,Report Type Description,Incident Status Code,Incident Status Description,Investigation Status,Incident Occurred,Incident Reported,Incident Location,...,Weapon Description,Victim Number,Domestic Related,Victim Type,Victim Description,Victim Gender,Victim Race,Victim Ethnicity,Victim County Resident,Mapped Location
0,20210237359_11,20210237359,D,DISPATCHED,O,OPEN,Open,2021-04-27 08:00:00,04/28/2021 02:08:00 PM,DIVISION ST,...,NONE,1,False,I,INDIVIDUAL (18 AND OVER),M,W,Hispanic,NON RESIDENT,POINT (-86.78 36.15)
1,20210248988_12,20210248988,D,DISPATCHED,O,OPEN,Open,2021-05-04 15:07:00,05/04/2021 04:26:00 PM,SHELBY AVE,...,NONE,2,False,I,INDIVIDUAL (18 AND OVER),F,W,Non-Hispanic,RESIDENT,POINT (-86.75 36.17)
2,20150345704_11,20150345704,T,NaN,O,OPEN,Open,2015-04-13 15:00:00,04/13/2015 05:12:00 PM,180 WALLACE RD,...,NONE,1,False,I,INDIVIDUAL (18 AND OVER),M,W,Non-Hispanic,RESIDENT,NaN
3,20210247765_11,20210247765,O,NaN,O,OPEN,Open,2021-05-03 23:00:00,05/03/2021 11:49:00 PM,CLARKSVILLE PIKE,...,NONE,1,False,I,INDIVIDUAL (18 AND OVER),M,W,Non-Hispanic,RESIDENT,POINT (-86.9 36.32)
4,20210249540_11,20210249540,D,DISPATCHED,O,OPEN,Open,2021-05-04 23:45:00,05/05/2021 12:45:00 AM,UNIVERSITY CT,...,PERSONAL (HANDS),1,False,I,INDIVIDUAL (18 AND OVER),F,B,Non-Hispanic,RESIDENT,POINT (-86.77 36.15)

In [15]:
nv.columns = nv.columns.str.lower().str.replace(" ", "_")

In [16]:
nv = nv.rename(columns={'primary_key': 'city', 'incident_occurred': 'date', 'offense_description': 'crime_category'})

In [17]:
nv['city'] = 'Nashville'

In [18]:
nv.columns

Index(['city', 'incident_number', 'report_type', 'report_type_description',
       'incident_status_code', 'incident_status_description',
       'investigation_status', 'date', 'incident_reported',
       'incident_location', 'latitude', 'longitude', 'zip_code', 'rpa', 'zone',
       'location_code', 'location_description', 'offense_number',
       'offense_nibrs', 'crime_category', 'weapon_primary',
       'weapon_description', 'victim_number', 'domestic_related',
       'victim_type', 'victim_description', 'victim_gender', 'victim_race',
       'victim_ethnicity', 'victim_county_resident', 'mapped_location'],
      dtype='object')

In [19]:
nv = nv.loc[:, ['city', 'date', 'crime_category', 'victim_gender', 'victim_race', 'victim_ethnicity']]

In [23]:
nv = nv[nv.date >= '2020-10-08']

In [24]:
nv

,city,date,crime_category,victim_gender,victim_race,victim_ethnicity
0,Nashville,2021-04-27 08:00:00,BURGLARY- MOTOR VEHICLE,M,W,Hispanic
1,Nashville,2021-05-04 15:07:00,HARRASSMENT (NUISANCE),F,W,Non-Hispanic
3,Nashville,2021-05-03 23:00:00,LARC - PARTS FROM VEH,M,W,Non-Hispanic
4,Nashville,2021-05-04 23:45:00,BURGLARY- AGGRAVATED,F,B,Non-Hispanic
5,Nashville,2021-05-01 23:00:00,SIMPLE ASSLT,M,A,Non-Hispanic
...,...,...,...,...,...,...
872288,Nashville,2020-10-20 15:00:00,BURGL - FORCED ENTRY-NONRESID,NaN,NaN,NaN
872298,Nashville,2021-01-25 12:52:00,"WEAPON OFFENSE, CRIMINAL ATTEMPT",NaN,NaN,NaN
872303,Nashville,2020-10-21 14:50:00,POLICE INQUIRY,F,W,Hispanic
872309,Nashville,2021-01-14 07:00:00,LOST PROPERTY,NaN,NaN,NaN
872313,Nashville,2020-12-18 18:06:00,POLICE INQUIRY,U,U,Non-Hispanic

In [ ]:
nv.to_csv('../Data_Clean/Nashville.csv')